<!-- statesman sitecatalyst to test blanks -->
<script language="JavaScript" type="text/javascript"><!--
if (projectCategory == "") {
	projectHier3 = projectChannel
}
else if (projectSubCategory == "" && projectCategory != "") {
	projectHier3 = projectChannel + "|" + projectCategory
}
else {
	projectHier3 = projectChannel + "|" + projectCategory + "|" + projectSubCategory
}
--></script>

<!-- SiteCatalyst code version: H.25.5.
Copyright 1996-2013 Adobe, Inc. All Rights Reserved
More info available at http://www.omniture.com -->
<script language="JavaScript" type="text/javascript" src="https://media.cmgdigital.com/shared/news/documents/2013/08/07/sitecatalyst_statesmanv25.js"></script>
<script language="JavaScript" type="text/javascript"><!--

/* You may give each page an identifying name, server, and channel on
the next lines. */

s.pageName=location.host + location.pathname
s.server=window.location.host
s.channel=projectChannel
s.pageType=""
s.prop9=window.location.host
s.prop13=document.title.toLowerCase()
s.prop14=projectCategory
s.prop16="non-mobile site"
s.prop17=""
s.prop18=""
s.prop19=""
s.prop20=""
s.prop21=projectSite
s.prop22="flat pages"
s.prop23=""
s.prop42=projectSite
s.prop43="newspaper"
s.prop57=document.referrer
s.prop63=document.location.href
/* Conversion Variables */
s.hier1="tx: austin|newspaper|" + projectSite
s.hier2="newspaper|tx: austin|" + projectSite
s.hier3=projectHier3
s.campaign=""
s.state=""
s.zip=""
s.events="event1"
s.products=""
s.purchaseID=""
s.eVar9=s.prop9
s.eVar13=s.prop13
s.eVar14=s.prop14
s.eVar15=""
s.eVar16="non-mobile site"
s.eVar17=""
s.eVar18=""
s.eVar19=""
s.eVar20=""
s.eVar21=s.prop21
s.eVar22="flat pages"
s.eVar23=""
s.eVar42=s.prop42
s.eVar43="newspaper"
s.eVar55=s.pageName
s.eVar56=s.channel
s.eVar57=document.referrer
s.eVar63=document.location.href


/************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/
var s_code=s.t();if(s_code)document.write(s_code)//--></script>
<script language="JavaScript" type="text/javascript"><!--
if(navigator.appVersion.indexOf('MSIE')>=0)document.write(unescape('%3C')+'\!-'+'-')
//--></script><noscript><img src="https://coxnet.112.2o7.net/b/ss/coxstatesman/1/H.25.5--NS/0"
height="1" width="1" border="0" alt="" /></noscript><!--/DO NOT REMOVE/-->
<!-- End SiteCatalyst code version: H.25.5. -->

<!-- Quantcast Tag, part 2 -->
<script type="text/javascript">
    _qevents.push( { qacct:"p-38KriKc8Foyx-"} );
</script>
<noscript>
<div style="display: none;">
    <img src="https://pixel.quantserve.com/pixel/p-test123.gif" height="1" width="1" alt="Quantcast"/>
</div>
</noscript>


<!-- begin janrain_override block -->
<i class="jsinclude" style="display:none" data-key="jr_backplaneBusName" data-value="coxmediagroup.com" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_backplaneVersion" data-value="" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_captureServer" data-value="https://cmg.janraincapture.com/" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_appId" data-value="6z4jnndkpe6dmfx7vdg4c7hkmz" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_federateServer" data-value="https://sso.cmgdigital.com" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_clientId" data-value="tne2pkkptqbyncx277kv37xqrwq36zqk" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_socialLoginAppId" data-value="acgbmfmhondnbilockca" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_socialLoginAppUrl" data-value="https://login.cmgdigital.com" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="currentSite" data-value="//www.mystatesman.com" data-literal="false"></i>
<!-- end janrain_override block -->
<!-- begin member_center_override block -->
<i class="jsinclude" style="display:none" data-key="mc_prod" data-value="true" data-literal="true"></i>
<i class="jsinclude" style="display:none" data-key="mc_connext_on" data-value="true" data-literal="true"></i>
<i class="jsinclude" style="display:none" data-key="mc_connext_meter_on" data-value="true" data-literal="true"></i>
<i class="jsinclude" style="display:none" data-key="mc_console_logging_enabled" data-value="true" data-literal="true"></i>
<!-- end member_center_override block -->
<!-- begin retargeting_pixels_footer_override block -->
<div class="retargeting-pixel retargeting-pixel-footer" style="display:none">
</div>
<!-- end retargeting_pixels_footer_override block -->
<!-- begin delayed_scripts_override block -->
<script type="text/javascript" src="//www.mystatesman.com/r/PortalConfig/np-paid/assets/js/minimalist.min.js"></script>
<!-- end delayed_scripts_override block -->
<!-- begin janrain_script_override block -->
<script async defer="defer" src="//widget-cdn.rpxnow.com/manifest/capture:login:share?version=1.111.0_widgets_503"></script>
<!-- end janrain_script_override block -->
<!-- begin ad_gpt_script_override block -->
<script async defer="defer" src="//www.googletagservices.com/tag/js/gpt.js"></script>
<!-- end ad_gpt_script_override block -->
<!-- begin ad_prebid_script_override block -->
<script async defer="defer" src="https://acdn.adnxs.com/prebid/c/6990/pb.js"></script>
<!-- end ad_prebid_script_override block -->
<!-- begin fb_script_override block -->
<script async defer="defer" src="//connect.facebook.net/en_US/all.js#xfbml=1" id="facebook-jssdk"></script>
<!-- end fb_script_override block -->
<!-- begin trueanthem_script_override block -->
<script src="//tru.am/scripts/custom/coxmedia.js"></script>
<!-- end trueanthem_script_override block -->
