<!-- statesman sitecatalyst to test blanks -->
<script language="JavaScript" type="text/javascript"><!--
if (projectCategory == "") {
	projectHier3 = projectChannel
}
else if (projectSubCategory == "" && projectCategory != "") {
	projectHier3 = projectChannel + "|" + projectCategory
}
else {
	projectHier3 = projectChannel + "|" + projectCategory + "|" + projectSubCategory
}
--></script>

<!-- SiteCatalyst code version: H.25.5.
Copyright 1996-2013 Adobe, Inc. All Rights Reserved
More info available at http://www.omniture.com -->
<script language="JavaScript" type="text/javascript" src="https://media.cmgdigital.com/shared/news/documents/2013/08/07/sitecatalyst_statesmanv25.js"></script>
<script language="JavaScript" type="text/javascript"><!--

/* You may give each page an identifying name, server, and channel on
the next lines. */

s.pageName=location.host + location.pathname
s.server=window.location.host
s.channel=projectChannel
s.pageType=""
s.prop9=window.location.host
s.prop13=document.title.toLowerCase()
s.prop14=projectCategory
s.prop16="non-mobile site"
s.prop17=""
s.prop18=""
s.prop19=""
s.prop20=""
s.prop21=projectSite
s.prop22="flat pages"
s.prop23=""
s.prop42=projectSite
s.prop43="newspaper"
s.prop57=document.referrer
s.prop63=document.location.href
/* Conversion Variables */
s.hier1="tx: austin|newspaper|" + projectSite
s.hier2="newspaper|tx: austin|" + projectSite
s.hier3=projectHier3
s.campaign=""
s.state=""
s.zip=""
s.events="event1"
s.products=""
s.purchaseID=""
s.eVar9=s.prop9
s.eVar13=s.prop13
s.eVar14=s.prop14
s.eVar15=""
s.eVar16="non-mobile site"
s.eVar17=""
s.eVar18=""
s.eVar19=""
s.eVar20=""
s.eVar21=s.prop21
s.eVar22="flat pages"
s.eVar23=""
s.eVar42=s.prop42
s.eVar43="newspaper"
s.eVar55=s.pageName
s.eVar56=s.channel
s.eVar57=document.referrer
s.eVar63=document.location.href


/************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/
var s_code=s.t();if(s_code)document.write(s_code)//--></script>
<script language="JavaScript" type="text/javascript"><!--
if(navigator.appVersion.indexOf('MSIE')>=0)document.write(unescape('%3C')+'\!-'+'-')
//--></script><noscript><img src="https://coxnet.112.2o7.net/b/ss/coxstatesman/1/H.25.5--NS/0"
height="1" width="1" border="0" alt="" /></noscript><!--/DO NOT REMOVE/-->
<!-- End SiteCatalyst code version: H.25.5. -->

<!-- Quantcast Tag, part 2 -->
<script type="text/javascript">
    _qevents.push( { qacct:"p-38KriKc8Foyx-"} );
</script>
<noscript>
<div style="display: none;">
    <img src="https://pixel.quantserve.com/pixel/p-test123.gif" height="1" width="1" alt="Quantcast"/>
</div>
</noscript>


<!-- begin janrain_override block -->
<i class="jsinclude" style="display:none" data-key="jr_backplaneBusName" data-value="coxmediagroup.com" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_backplaneVersion" data-value="" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_captureServer" data-value="https://cmg.janraincapture.com/" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_appId" data-value="6z4jnndkpe6dmfx7vdg4c7hkmz" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_federateServer" data-value="https://sso.cmgdigital.com" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_clientId" data-value="tne2pkkptqbyncx277kv37xqrwq36zqk" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_socialLoginAppId" data-value="acgbmfmhondnbilockca" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="jr_socialLoginAppUrl" data-value="https://login.cmgdigital.com" data-literal="false"></i>
<i class="jsinclude" style="display:none" data-key="currentSite" data-value="//www.mystatesman.com" data-literal="false"></i>
<div style="display:none" id="signIn">
<div class="cm-janrain-wrapper">
<div id="signIn_Container">
<div class="cm-janrain-header">
<img src="//www.mystatesman.com/r/PortalConfig/np-paid/assets/mystatesman/images/logo-black.svg" name="myStatesman.com" class="header-logo" alt="myStatesman.com">
<span class="cm-janrain-h1">Sign In</span>
</div>
<div class="container-fluid">
<div class="row">
<div class="col-lg-14"></div>
<div class="col-lg-4">
<div class="cm-janrain-or-divider">OR</div>
</div>
<div class="col-lg-14"></div>
<div class="cm-login">
<h2>Sign in using your myStatesman.com profile</h2>
<p>
Need a Profile?
<a href="#" id="cmJanrainRegistration" data-capturescreen="traditionalRegistration">Register Now.</a>
</p>
{* #userInformationForm *}
<div class="cm-form-label">*EMAIL</div>
{* traditionalSignIn_emailAddress *}
<div class="cm-form-label">*PASSWORD</div>
<a href="#" data-capturescreen="forgotPassword">Forgot your password?</a>
{* traditionalSignIn_password *} {* traditionalSignIn_signInButton *} {* /userInformationForm *}
</div>
<div class="cm-social-login">
<h2>Sign in using your existing account</h2>
{* loginWidget *}
</div>
</div>
</div>
</div>
</div>
</div>
<div style="display:none" id="returnSocial">
<div class="cm-janrain-wrapper">
<div id="signIn_Container">
<div class="cm-janrain-header">
<img src="//www.mystatesman.com/r/PortalConfig/np-paid/assets/mystatesman/images/logo-black.svg" name="myStatesman.com" class="header-logo" alt="myStatesman.com">
<span class="cm-janrain-h1">Sign In</span>
</div>
<div class="container-fluid">
<div class="row">
<div class="col-lg-14"></div>
<div class="col-lg-4">
<div class="cm-janrain-or-divider">OR</div>
</div>
<div class="col-lg-14"></div>
<div class="cm-login">
<h2>Sign in using your myStatesman.com profile</h2>
<p>
Need a Profile?
<a href="#" id="cmJanrainRegistration" data-capturescreen="traditionalRegistration">Register Now.</a>
</p>
{* #userInformationForm *}
<div class="cm-form-label">*EMAIL</div>
{* traditionalSignIn_emailAddress *}
<div class="cm-form-label">*PASSWORD</div>
<a href="#" data-capturescreen="forgotPassword">Forgot your password?</a>
{* traditionalSignIn_password *} {* traditionalSignIn_signInButton *} {* /userInformationForm *}
</div>
<div class="cm-social-login">
<h2>Sign in using your existing account</h2>
{* loginWidget *}
</div>
</div>
</div>
</div>
</div>
</div>
<div style="display:none" id="returnTraditional">
<div class="cm-janrain-wrapper">
<div id="signIn_Container">
<div class="cm-janrain-header">
<img src="//www.mystatesman.com/r/PortalConfig/np-paid/assets/mystatesman/images/logo-black.svg" name="myStatesman.com" class="header-logo" alt="myStatesman.com">
<span class="cm-janrain-h1">Sign In</span>
</div>
<div class="container-fluid">
<div class="row">
<div class="col-lg-14"></div>
<div class="col-lg-4">
<div class="cm-janrain-or-divider">OR</div>
</div>
<div class="col-lg-14"></div>
<div class="cm-login">
<h2>Sign in using your myStatesman.com profile</h2>
<p>
Need a Profile?
<a href="#" id="cmJanrainRegistration" data-capturescreen="traditionalRegistration">Register Now.</a>
</p>
{* #userInformationForm *}
<div class="cm-form-label">*EMAIL</div>
{* traditionalSignIn_emailAddress *}
<div class="cm-form-label">*PASSWORD</div>
<a href="#" data-capturescreen="forgotPassword">Forgot your password?</a>
{* traditionalSignIn_password *} {* traditionalSignIn_signInButton *} {* /userInformationForm *}
</div>
<div class="cm-social-login">
<h2>Sign in using your existing account</h2>
{* loginWidget *}
</div>
</div>
</div>
</div>
</div>
</div>
<div style="display:none" id="socialRegistration">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">You're Almost Done!</span>
<h2>Please confirm the information below before signing in.</h2>
<div class="cm-janrain-required">*Required</div>
{* #socialRegistrationForm *} {* socialRegistration_displayName *} {* socialRegistration_emailAddress *}
<div class="cm-janrain-tocnotice">
By submitting your registration information, you agree to our
<a href="//www.mystatesman.com/visitor_agreement/" target="_blank">Visitor Agreement</a>
and
<a href="//www.mystatesman.com/privacy_policy/" target="_blank">Privacy Policy</a>.
</div>
{* socialRegistration_signInButton *} {* /socialRegistrationForm *}
</div>
</div>
<div style="display:none" id="traditionalRegistration">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Register</span>
<div class="cm-janrain-required">*Required</div>
{* #registrationForm *} {* traditionalRegistration_emailAddress *} {* traditionalRegistration_password *} {* traditionalRegistration_passwordConfirm *} {* traditionalRegistration_displayName *}
<div class="cm-janrain-tocnotice">
By submitting your registration information, you agree to our
<a href="//www.mystatesman.com/visitor_agreement/" target="_blank">Visitor Agreement</a>
and
<a href="//www.mystatesman.com/privacy_policy/" target="_blank">Privacy Policy</a>.
</div>
{* createAccountButton *} {* /registrationForm *}
</div>
</div>
<div style="display:none" id="traditionalRegistrationBlank">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Create a New Account</span>
<div class="cm-janrain-required">*Required</div>
{* #registrationFormBlank *} {* traditionalRegistration_emailAddressBlank *} {* traditionalRegistration_passwordBlank *} {* traditionalRegistration_passwordConfirmBlank *} {* traditionalRegistration_displayName *}
<div class="cm-janrain-tocnotice">
By submitting your registration information, you agree to our
<a href="//www.mystatesman.com/visitor_agreement/" target="_blank">Visitor Agreement</a>
and
<a href="//www.mystatesman.com/privacy_policy/" target="_blank">Privacy Policy</a>.
</div>
{* createAccountButton *} {* /registrationForm *}
</div>
</div>
<div style="display:none" id="registrationSuccess">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Just One More Thing...</span>
<p>We have sent you a verification email. Please check your email and click on the link to activate your profile.</p>
<p>If you do not receive the verification message within a few minutes of signing up, please check your Spam or Junk folder.</p>
<span onclick="janrain.capture.ui.modal.close()" class="capture_btn capture_primary">Close</span>
</div>
</div>
<div style="display:none" id="registrationSuccessConfirmed">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Thank you for registering!</span>
<p>We look forward to seeing you on [website] frequently. Visit us and sign in to update your profile, receive the latest news and keep up to date with mobile alerts.</p>
<p>
Click <a href="javascript:;" onclick="janrain.capture.ui.modal.close();return false;">here</a> to return to the page you were visiting.
</p>
</div>
</div>
<div style="display:none" id="forgotPassword">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Create a new password</span>
<p>Don't worry, it happens. We'll send you a link to create a new password.</p>
{* #forgotPasswordForm *} {* forgotPassword_emailAddress *} {* forgotPassword_sendButton *} {* /forgotPasswordForm *}
</div>
</div>
<div style="display:none" id="forgotPasswordSuccess">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Email sent</span>
<p>We have sent you an email with a link to change your password.</p>
<a href="#" onclick="janrain.capture.ui.modal.close()" class="capture_btn capture_primary">Close</a>
</div>
</div>
<div style="display:none" id="resetPassword">
<div class="cm-janrain-wrapper" datatype="changePasswordLink">
<span class="cm-janrain-h1">Change password</span>
{* newPasswordForm *} {* newPassword *} {* newPasswordConfirm *} {* submitButton *} {* /newPasswordForm *}
</div>
</div><div style="display:none" id="resetPasswordSuccess">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Your password has been changed</span>
<p>Password has been successfully updated.</p>
<a href="#" class="cmOpenJanrainModal capture_btn capture_primary">Sign in</a>
</div>
</div><div style="display:none" id="resetPasswordRequestCode">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Create a new password</span>
<p>We didn't recognize that password reset code. Enter your email address to get a new one.</p>
{* #forgotPasswordForm *} {* forgotPassword_emailAddress *} {* forgotPassword_sendButton *} {* /forgotPasswordForm *}
</div>
</div><div style="display:none" id="resetPasswordRequestCodeSuccess">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Create a new password</span>
<p>We've sent an email with instructions to create a new password. Your existing password has not been changed.</p>
<a href="#" onclick="janrain.capture.ui.modal.close()" class="capture_btn capture_primary">Close</a>
</div>
</div><div style="display:none" id="mergeAccounts">
{* mergeAccounts *}
</div>
<div style="display:none" id="traditionalAuthenticateMerge">
<div class="cm-janrain-wrapper">
<span class="cm-janrain-h1">Sign in to complete account merge</span>
{* #tradAuthenticateMergeForm *} {* traditionalSignIn_emailAddress *} {* mergePassword *} {* backButton *} {* traditionalSignIn_signInButton *} {* /tradAuthenticateMergeForm *}
</div>
</div>
<div style="display:none" id="resendVerification">
<div class="cm-janrain-wrapper">
<div class="capture_header">
<span class="cm-janrain-h1">Resend Email Verification</span>
</div>
<p>Click submit to receive another verification email</p>
{* #resendVerificationForm *} {* traditionalSignIn_emailAddress *}
<div class="capture_footer">
<input type="submit" value="Submit" class="capture_btn capture_primary">
</div>
{* /resendVerificationForm *}
</div>
</div>
<div style="display:none" id="resendVerificationSuccess">
<div class="cm-janrain-wrapper">
<div class="capture_header">
<span class="cm-janrain-h1">Your Verification Email Has Been Sent</span>
</div>
<div class="hr"></div>
<p>Check your email for a verification link</p>
<div class="capture_footer">
<button onclick="janrain.capture.ui.modal.close()" class="capture_btn capture_primary">Close</button>
</div>
</div>
</div>
<div style="display: none" id="verifyEmail">
<div class="verify-email">
<h1>Whoa there!</h1>
<p>Looks like you're already verified.</p>
<p>If you still have trouble signing in, you probably need a new confirmation link email.</p>
<p>{* resendLink *} Please resend verification.</p>
</div>
</div><div style="display: none" id="verifyEmailSuccess">
<div class="verify-email">
<h1>Thanks for verifying your email address</h1>
<p>You're now logged in.</p>
<p>LINK YOUR ACCOUNT FOR PREMIUM ACCESS</p>
<p>Are you already a home delivery subscriber for myStatesman.com?</p>
<div class="verify-email-buttons"><a id="dss_url_methode" class="more-section-bg" href="https://myaccount.statesman.com/dssmatch.aspx?em=">Yes, Link My Account</a><button onclick="janrain.capture.ui.modal.close()" class="more-section-bg">No, I'm good</button></div>
</div>
</div><!-- end janrain_override block -->
<!-- begin member_center_override block -->
<i class="jsinclude" style="display:none" data-key="mc_prod" data-value="true" data-literal="true"></i>
<i class="jsinclude" style="display:none" data-key="mc_connext_on" data-value="true" data-literal="true"></i>
<i class="jsinclude" style="display:none" data-key="mc_connext_meter_on" data-value="true" data-literal="true"></i>
<i class="jsinclude" style="display:none" data-key="mc_console_logging_enabled" data-value="true" data-literal="true"></i>
<!-- end member_center_override block -->
<!-- begin retargeting_pixels_footer_override block -->
<div class="retargeting-pixel retargeting-pixel-footer" style="display:none">
</div>
<!-- end retargeting_pixels_footer_override block -->
<!-- begin delayed_scripts_override block -->
<script type="text/javascript" src="//www.mystatesman.com/r/PortalConfig/np-paid/assets/js/minimalist.min.js"></script>
<!-- end delayed_scripts_override block -->
<!-- begin janrain_script_override block -->
<script async defer="defer" src="//widget-cdn.rpxnow.com/manifest/capture:login:share?version=1.111.0_widgets_503"></script>
<!-- end janrain_script_override block -->
<!-- begin ad_gpt_script_override block -->
<script async defer="defer" src="//www.googletagservices.com/tag/js/gpt.js"></script>
<!-- end ad_gpt_script_override block -->
<!-- begin ad_prebid_script_override block -->
<script async defer="defer" src="https://acdn.adnxs.com/prebid/c/6990/pb.js"></script>
<!-- end ad_prebid_script_override block -->
<!-- begin fb_script_override block -->
<script async defer="defer" src="//connect.facebook.net/en_US/all.js#xfbml=1" id="facebook-jssdk"></script>
<!-- end fb_script_override block -->
<!-- begin trueanthem_script_override block -->
<script src="//tru.am/scripts/custom/coxmedia.js"></script>
<!-- end trueanthem_script_override block -->
