<script type="text/javascript">
  var projectSite = "statesman";
  var projectChannel = "news";
  var projectCategory = "local";
  var projectSubCategory = "zandan-poll-2017"; // name for specific project
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-66319610-2', 'auto');
  ga('send', 'pageview');
</script>
